Repository gridsuite/gridstudy-app, pull requests merged in 2020-03, with the labels that each got.

#39 keep_the_same_zoom_level_for_substation_with_an_activable_scroll
  src/components/single-line-diagram.js
Labels: PR: ready-to-be-merged, enhancement

#57 In the study list page: Truncate the card names, and add description/…
  package.json
  src/components/study-manager.js
  src/redux/reducer.js
  src/translations/en.json
  src/translations/fr.json
Labels: good first issue

#62 Modification of the substation list to adapt to the web browser height
  package.json
  src/components/network/network-explorer.js
Labels: enhancement
