Repository gridsuite/gridstudy-app, pull requests merged in 2020-11, with the labels that each got.

#254 add navigation arrows
  src/components/app.js
  src/components/single-line-diagram.js
  src/images/arrow.svg
  src/images/arrow_hover.svg
  src/translations/en.json
  src/translations/fr.json
Labels: PR: waiting-for-review

#242 apps-metadata-updates
  .env
  app-httpd.conf
  public/env.json
  src/setupProxy.js
  src/utils/rest-api.js
Labels: S

#260 fix navigation arrows
  src/components/single-line-diagram.js
Labels: PR: waiting-for-review, S

#267 Add owner
  src/components/access-rights-dialog.js
  src/components/study-manager.js
  src/translations/en.json
  src/translations/fr.json
Labels: S
